### ISSUE TITLE
v1.1 errata

### ISSUE THREAD

**Issue by gkasprow** [elhep/SiPM_AFE#6]
- [x] wrong SIPM footprint - we are using 3mm sensors, not 1.3mm ones (S13360-3075PE INSTEAD OF S13360-1375PE)

**Comment by gkasprow** [comment]
- [x] connect CC lines to CPU. Wrong PCB version was manufactured.

**Comment by Marcinb10** [comment]
O która płytkę chodzi?
i jaki konkretnie jest problem to znaczy co nie będzie działać?
Dlaczego zła płytka była wyprodukowana?
Marcin

**Comment by Marcinb10** [comment]
Czy na etapie budowy demonstratora (obecny zestaw płytek) da się ten problem rozwiązać robiąc poprawki bezposrednio na płytce (lutownica) czy wymaga to zamówienie nowych płytek?

**Comment by gkasprow** [comment]
It's a matter of USB plug polarity detection. It will be fixed with a piece of thin wire. It's not an important feature added at the last moment to the design when the PCB was already in production

**Comment by Marcinb10** [comment]
OK Thanku you

**Comment by gkasprow** [comment]
added temp ADC decoupling capacitors, just in case, because the temperature measurement is not working yet
